### ISSUE TITLE
Mention opam-ocsigen repo in README?

### ISSUE THREAD

**Issue by mlinksva** [ocsigen/eliom-base-app#26]
I got nowhere close to building before happening to notice at https://github.com/ocsigen/eliom-base-app/issues/24#issuecomment-62711652 "Please use the opam-ocsigen repo:"

```
opam repo add ocsigen-dev git://github.com/ocsigen/opam-ocsigen
opam install eliom-base-app
```

Should this be added to the README while that is necessary? Would have saved me some time, and presumably others taking a look at the project for the first time.

**Comment by balat** [comment]
Thanks for the report. I've added this in README. Also Eliom-base-app now depends on branch sharedreact of Eliom.
